//! # Backtester Core
//!
//! Fundamental types, traits, and event definitions for the backtesting engine.
//!
//! This crate is the central dependency for all other crates in the workspace.
//! It defines the contracts that components must implement.

#![deny(unsafe_code)]
#![warn(missing_docs)]
#![warn(clippy::pedantic)]

/// Nanoseconds since UNIX epoch (UTC).
/// All internal timestamps use this representation for determinism.
pub type Timestamp = i64;

/// Asset identifier (integer for cache-friendly access).
pub type AssetId = u32;

/// OHLCV bar data.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Bar {
    /// Timestamp in nanoseconds (UTC)
    pub timestamp: Timestamp,
    /// Opening price
    pub open: f64,
    /// Highest price
    pub high: f64,
    /// Lowest price
    pub low: f64,
    /// Closing price
    pub close: f64,
    /// Volume
    pub volume: f64,
}

impl Bar {
    /// Calculate typical price (H+L+C)/3.
    #[must_use]
    pub fn typical_price(&self) -> f64 {
        (self.high + self.low + self.close) / 3.0
    }

    /// Calculate bar range (high - low).
    #[must_use]
    pub fn range(&self) -> f64 {
        self.high - self.low
    }

    /// Calculate VWAP approximation using typical price.
    #[must_use]
    pub fn vwap_approx(&self) -> f64 {
        self.typical_price()
    }
}

/// Event types processed by the simulation engine.
#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    /// Market data update
    Market(MarketEvent),
    /// Trading signal from strategy
    Signal(SignalEvent),
    /// Order to execute
    Order(OrderEvent),
    /// Executed fill
    Fill(FillEvent),
    /// Session close event
    SessionClose(SessionCloseEvent),
}

/// Market data event (bar update for an asset).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MarketEvent {
    /// Asset identifier
    pub asset_id: AssetId,
    /// Bar data
    pub bar: Bar,
}

/// Session close event (end of trading day).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SessionCloseEvent {
    /// Timestamp of session close
    pub timestamp: Timestamp,
}

/// Signal direction.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SignalDirection {
    /// Buy signal
    Buy,
    /// Sell signal
    Sell,
    /// Neutral / no signal
    Neutral,
}

/// Signal generated by a strategy.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SignalEvent {
    /// Timestamp when signal was generated
    pub timestamp: Timestamp,
    /// Target asset
    pub asset_id: AssetId,
    /// Signal strength (-1.0 to 1.0, negative = sell, positive = buy)
    pub strength: f64,
}

impl SignalEvent {
    /// Get signal direction.
    #[must_use]
    pub fn direction(&self) -> SignalDirection {
        if self.strength > 0.0 {
            SignalDirection::Buy
        } else if self.strength < 0.0 {
            SignalDirection::Sell
        } else {
            SignalDirection::Neutral
        }
    }
}

/// Order side.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Side {
    /// Buy order
    Buy,
    /// Sell order
    Sell,
}

/// Order type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderType {
    /// Market order - execute at best available price
    Market,
    /// Limit order - execute at specified price or better
    Limit,
}

/// Order to be executed.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct OrderEvent {
    /// Timestamp when order was created
    pub timestamp: Timestamp,
    /// Target asset
    pub asset_id: AssetId,
    /// Quantity (positive = buy, negative = sell). Must be multiple of 100 for B3.
    pub quantity: i64,
    /// Limit price (if applicable)
    pub limit_price: Option<f64>,
}

impl OrderEvent {
    /// Get order side.
    #[must_use]
    pub fn side(&self) -> Side {
        if self.quantity > 0 {
            Side::Buy
        } else {
            Side::Sell
        }
    }

    /// Get order type.
    #[must_use]
    pub fn order_type(&self) -> OrderType {
        if self.limit_price.is_some() {
            OrderType::Limit
        } else {
            OrderType::Market
        }
    }

    /// Validate B3 round-lot requirement.
    #[must_use]
    pub fn is_valid_b3_lot(&self) -> bool {
        self.quantity != 0 && self.quantity % 100 == 0
    }
}

/// Executed fill.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct FillEvent {
    /// Timestamp when fill occurred
    pub timestamp: Timestamp,
    /// Asset that was filled
    pub asset_id: AssetId,
    /// Filled quantity
    pub quantity: i64,
    /// Execution price
    pub price: f64,
    /// Total cost (fees, commissions)
    pub cost: f64,
}

impl FillEvent {
    /// Calculate notional value of fill.
    #[must_use]
    #[allow(clippy::cast_precision_loss)]
    pub fn notional(&self) -> f64 {
        self.quantity.abs() as f64 * self.price
    }
}

/// Order request from strategy (before sizing/routing).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct OrderRequest {
    /// Target asset
    pub asset_id: AssetId,
    /// Direction
    pub side: Side,
    /// Desired quantity (may be adjusted by router)
    pub quantity: i64,
    /// Order type
    pub order_type: OrderType,
    /// Limit price (for limit orders)
    pub limit_price: Option<f64>,
}

/// Strategy configuration passed during initialization.
#[derive(Debug, Clone, Default)]
pub struct StrategyConfig {
    /// Strategy parameters as key-value pairs
    pub params: Vec<(String, f64)>,
}

impl StrategyConfig {
    /// Get a parameter value.
    #[must_use]
    pub fn get(&self, key: &str) -> Option<f64> {
        self.params.iter().find(|(k, _)| k == key).map(|(_, v)| *v)
    }

    /// Get a parameter with default value.
    #[must_use]
    pub fn get_or(&self, key: &str, default: f64) -> f64 {
        self.get(key).unwrap_or(default)
    }
}

/// Strategy trait - must be implemented by user strategies.
///
/// # Lifecycle
/// 1. `on_init` - Called once at backtest start
/// 2. `on_market` - Called for each market event (hot path)
/// 3. `on_session_close` - Called at end of each trading session
/// 4. `on_backtest_end` - Called once at backtest end
///
/// # Contracts
/// - Hot path methods (`on_market`, `on_session_close`) must be allocation-free
/// - No I/O allowed in hot path
/// - Must be deterministic (no unseeded RNG, no system time access)
pub trait Strategy {
    /// Called once at the start of the backtest.
    /// Use this for initialization and buffer pre-allocation.
    fn on_init(&mut self, _config: &StrategyConfig, _num_assets: usize) {
        // Default: no-op
    }

    /// Called for each market event. Returns optional signal.
    /// This is the hot path - must be fast and allocation-free.
    fn on_market(&mut self, event: &MarketEvent) -> Option<SignalEvent>;

    /// Called at the end of each trading session.
    /// Use this for net-zero strategies to close positions.
    fn on_session_close(&mut self, _timestamp: Timestamp, _asset_id: AssetId) -> Option<SignalEvent> {
        None
    }

    /// Called once at the end of the backtest.
    /// Use this for cleanup and final logging.
    fn on_backtest_end(&mut self) {
        // Default: no-op
    }

    /// Get strategy name for logging/identification.
    fn name(&self) -> &str {
        "UnnamedStrategy"
    }
}

/// Execution model trait - simulates order fills with slippage/costs.
pub trait ExecutionModel {
    /// Simulate execution of an order, returning the fill.
    fn execute(&self, order: &OrderEvent, current_bar: &Bar) -> Option<FillEvent>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bar_creation() {
        let bar = Bar {
            timestamp: 1_700_000_000_000_000_000,
            open: 100.0,
            high: 105.0,
            low: 99.0,
            close: 104.0,
            volume: 10000.0,
        };
        assert!((bar.close - 104.0).abs() < f64::EPSILON);
        assert!((bar.range() - 6.0).abs() < f64::EPSILON);
    }

    #[test]
    fn event_enum_size() {
        // Ensure Event enum is reasonably sized for cache efficiency
        assert!(std::mem::size_of::<Event>() <= 128);
    }

    #[test]
    fn order_b3_lot_validation() {
        let valid = OrderEvent {
            timestamp: 0,
            asset_id: 0,
            quantity: 100,
            limit_price: None,
        };
        assert!(valid.is_valid_b3_lot());

        let invalid = OrderEvent {
            timestamp: 0,
            asset_id: 0,
            quantity: 50,
            limit_price: None,
        };
        assert!(!invalid.is_valid_b3_lot());
    }

    #[test]
    fn signal_direction() {
        let buy = SignalEvent {
            timestamp: 0,
            asset_id: 0,
            strength: 0.5,
        };
        assert_eq!(buy.direction(), SignalDirection::Buy);

        let sell = SignalEvent {
            timestamp: 0,
            asset_id: 0,
            strength: -0.5,
        };
        assert_eq!(sell.direction(), SignalDirection::Sell);
    }
}
