"""
Clean, Generic BaseStrategy for Brazilian Market Backtesting Framework

This module provides a minimal but complete interface that any strategy can implement.
The BaseStrategy class is designed to be framework-level and contains zero strategy-specific logic.

Key Features:
- Minimal interface with clear lifecycle hooks
- Zero strategy-specific code
- Integration with existing engine components
- Brazilian market compliance through context objects
- Type-safe and well-documented

Author: Quantitative Trading Specialist
Date: 2024
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, List, Tuple, Union, Iterable, Sequence
from datetime import datetime, date
from dataclasses import dataclass, field
import logging
from enum import Enum
import pandas as pd

# Configure logging
logger = logging.getLogger(__name__)


class OrderType(Enum):
    """Order types for Brazilian market."""
    MARKET = "market"
    LIMIT = "limit"


class OrderSide(Enum):
    """Order sides."""
    BUY = "buy"
    SELL = "sell"


@dataclass
class Bar:
    """
    Market data bar with OHLCV information.
    
    Attributes:
        symbol: Trading symbol (e.g., 'PETR4')
        timestamp: Bar timestamp
        open: Opening price
        high: High price
        low: Low price
        close: Closing price
        volume: Trading volume
        metadata: Additional bar metadata
    """
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Fill:
    """
    Order fill information.
    
    Attributes:
        order_id: Unique order identifier
        symbol: Trading symbol
        side: Order side (buy/sell)
        quantity: Filled quantity
        price: Fill price
        timestamp: Fill timestamp
        commission: Transaction commission
        metadata: Additional fill metadata
    """
    order_id: str
    symbol: str
    side: OrderSide
    quantity: int
    price: float
    timestamp: datetime
    commission: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class OrderIntent:
    """
    Order intent generated by strategy.
    
    Attributes:
        symbol: Trading symbol
        side: Order side (buy/sell)
        quantity: Order quantity
        order_type: Order type (market/limit)
        price: Limit price (if applicable)
        timestamp: Order timestamp
        metadata: Additional order metadata
    """
    symbol: str
    side: OrderSide
    quantity: int
    order_type: OrderType
    price: Optional[float] = None
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


class DataPortal(ABC):
    """
    Abstract data portal interface for strategy data access.
    
    This interface provides strategies with access to market data,
    historical data, and other data sources needed for decision making.
    """
    
    @abstractmethod
    def get_current_price(self, symbol: str) -> Optional[float]:
        """Get current market price for a symbol."""
        pass
    
    @abstractmethod
    def get_historical_data(self, symbol: str, start_date: datetime, end_date: datetime) -> Optional[pd.DataFrame]:
        """Get historical market data for a symbol."""
        pass
    
    @abstractmethod
    def get_market_data(self, symbol: str, timestamp: datetime) -> Optional[Dict[str, Any]]:
        """Get market data for a specific symbol and timestamp."""
        pass


class BrokerSimulation(ABC):
    """
    Abstract broker simulation interface for order management.
    
    This interface provides strategies with order execution simulation
    and position management capabilities.
    """
    
    @abstractmethod
    def submit_order(self, intent: 'OrderIntent') -> str:
        """Submit an order intent and return order ID."""
        pass
    
    @abstractmethod
    def get_position(self, symbol: str) -> Optional[Dict[str, Any]]:
        """Get current position information for a symbol."""
        pass
    
    @abstractmethod
    def get_cash_balance(self) -> float:
        """Get current cash balance."""
        pass
    
    @abstractmethod
    def get_portfolio_value(self) -> float:
        """Get total portfolio value."""
        pass


@dataclass
class StrategyConfig:
    """
    Immutable runtime parameters for strategy configuration.
    
    Attributes:
        universe: List of symbols to trade
        warmup_bars: Number of bars needed for warmup
        risk_tolerance: Risk tolerance level (0.0 to 1.0)
        max_position_size: Maximum position size as percentage of portfolio
        max_daily_loss: Maximum daily loss limit
        stop_loss_pct: Stop loss percentage
        take_profit_pct: Take profit percentage
        metadata: Additional configuration metadata
    """
    universe: List[str]
    warmup_bars: int = 20
    risk_tolerance: float = 0.02
    max_position_size: float = 0.1
    max_daily_loss: float = 0.02
    stop_loss_pct: float = 0.05
    take_profit_pct: float = 0.10
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate configuration parameters."""
        if not 0.0 <= self.risk_tolerance <= 1.0:
            raise ValueError("Risk tolerance must be between 0.0 and 1.0")
        
        if not 0.0 <= self.max_position_size <= 1.0:
            raise ValueError("Max position size must be between 0.0 and 1.0")
        
        if self.warmup_bars < 0:
            raise ValueError("Warmup bars must be non-negative")


@dataclass
class StrategyContext:
    """
    Live handles and context for strategy execution.
    
    Attributes:
        data_portal: Data access interface
        portfolio: Portfolio management interface
        broker: Broker simulation interface
        market_rules: Market rules and validation
        logger: Strategy-specific logger
        metadata: Additional context metadata
    """
    data_portal: Optional[DataPortal]  # Data access interface
    portfolio: Any    # Portfolio management interface
    broker: Optional[BrokerSimulation]       # Broker simulation interface
    market_rules: Any # Market rules and validation
    logger: logging.Logger
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.
    
    This class provides a minimal but complete interface that any strategy can implement.
    It contains zero strategy-specific logic and delegates all specialized functionality
    to the context objects (portfolio, broker, market_rules, etc.).
    
    Key Features:
    - Clean separation of concerns
    - Framework-level design
    - Brazilian market compliance through context
    - Comprehensive lifecycle hooks
    - Type-safe interface
    
    Usage:
        class MyStrategy(BaseStrategy):
            def generate_intents(self, bar: Bar) -> Iterable[OrderIntent]:
                # Implement your strategy logic here
                pass
    """
    
    def __init__(self, cfg: StrategyConfig, ctx: StrategyContext):
        """
        Initialize the strategy with configuration and context.
        
        Args:
            cfg: Immutable runtime parameters
            ctx: Live handles for data, portfolio, broker, etc.
        """
        # Validate inputs
        if not isinstance(cfg, StrategyConfig):
            raise TypeError("cfg must be a StrategyConfig instance")
        
        if not isinstance(ctx, StrategyContext):
            raise TypeError("ctx must be a StrategyContext instance")
        
        # Store configuration and context
        self._config = cfg
        self._context = ctx
        
        # Initialize internal state
        self._state: Dict[str, Any] = {}
        
        # Log initialization
        ctx.logger.info(f"Strategy '{self.name}' initialized")
        ctx.logger.info(f"Universe: {len(cfg.universe)} symbols")
        ctx.logger.info(f"Warmup bars: {cfg.warmup_bars}")
        ctx.logger.info(f"Risk tolerance: {cfg.risk_tolerance:.2%}")
    
    @property
    def name(self) -> str:
        """
        Strategy name (unique, short identifier).
        
        Returns:
            Strategy name, defaults to class name
        """
        return self.__class__.__name__
    
    @property
    def warmup_bars(self) -> int:
        """
        Number of bars needed for strategy warmup.
        
        Returns:
            Warmup bar count from configuration
        """
        return self._config.warmup_bars
    
    @property
    def config(self) -> StrategyConfig:
        """
        Strategy configuration (immutable).
        
        Returns:
            Strategy configuration
        """
        return self._config
    
    @property
    def context(self) -> StrategyContext:
        """
        Strategy context with live handles.
        
        Returns:
            Strategy context
        """
        return self._context
    
    @property
    def state(self) -> Dict[str, Any]:
        """
        Strategy internal state (small, serializable bag).
        
        Returns:
            Strategy state dictionary
        """
        return self._state
    
    # Lifecycle hooks (optional overrides)
    
    def on_start(self, asof: datetime) -> None:
        """
        Called when strategy starts.
        
        Override this method to perform strategy initialization.
        
        Args:
            asof: Strategy start timestamp
        """
        self.context.logger.info(f"Strategy '{self.name}' started at {asof}")
    
    def on_warmup(self, symbol: str, bars: Sequence[Bar]) -> None:
        """
        Called during warmup period for each symbol.
        
        Override this method to initialize indicators or perform warmup calculations.
        
        Args:
            symbol: Trading symbol
            bars: Historical bars for warmup
        """
        self.context.logger.debug(f"Warmup for {symbol}: {len(bars)} bars")
    
    def on_fill(self, fill: Fill) -> None:
        """
        Called when an order is filled.
        
        Override this method to react to fills (e.g., update state, log trades).
        
        Args:
            fill: Fill information
        """
        self.context.logger.info(f"Fill: {fill.symbol} {fill.side.value} "
                               f"{fill.quantity} @ {fill.price:.2f}")
    
    def on_end_of_day(self, d: date) -> Iterable[OrderIntent]:
        """
        Called at the end of each trading day.
        
        Override this method to implement day-trade flattening logic
        or other end-of-day operations.
        
        Args:
            d: Trading date
            
        Returns:
            Iterable of order intents for end-of-day operations
        """
        self.context.logger.debug(f"End of day: {d}")
        return []
    
    def on_end(self, asof: datetime) -> None:
        """
        Called when strategy ends.
        
        Override this method to perform cleanup or final calculations.
        
        Args:
            asof: Strategy end timestamp
        """
        self.context.logger.info(f"Strategy '{self.name}' ended at {asof}")
    
    # Must-implement abstract method
    
    @abstractmethod
    def generate_intents(self, bar: Bar) -> Iterable[OrderIntent]:
        """
        Generate order intents based on market data.
        
        This is the core method that concrete strategies must implement.
        It should analyze the current bar and return order intents.
        
        The method should be deterministic (pure function + state) and
        should not have side effects beyond updating internal state.
        
        Args:
            bar: Current market data bar
            
        Returns:
            Iterable of order intents
            
        Raises:
            NotImplementedError: Must be implemented by concrete strategies
        """
        pass
    
    # Convenience hooks with sensible defaults
    
    def size_intent(self, intent: OrderIntent, bar: Bar) -> OrderIntent:
        """
        Size an order intent based on portfolio constraints.
        
        This method provides sensible defaults for position sizing.
        Override for custom sizing logic.
        
        Args:
            intent: Original order intent
            bar: Current market data bar
            
        Returns:
            Sized order intent
        """
        # Get portfolio value
        portfolio_value = self.context.portfolio.get_portfolio_value()
        
        # Calculate maximum position value
        max_position_value = portfolio_value * self.config.max_position_size
        
        # Calculate position value based on intent
        position_value = min(
            intent.price * intent.quantity if intent.price else bar.close * intent.quantity,
            max_position_value
        )
        
        # Calculate quantity
        price = intent.price if intent.price else bar.close
        quantity = int(position_value / price)
        
        # Ensure minimum quantity
        if quantity < 1:
            quantity = 0
        
        # Create sized intent
        sized_intent = OrderIntent(
            symbol=intent.symbol,
            side=intent.side,
            quantity=quantity,
            order_type=intent.order_type,
            price=intent.price,
            timestamp=intent.timestamp,
            metadata=intent.metadata
        )
        
        self.context.logger.debug(f"Sized intent: {quantity} shares (value: R$ {position_value:,.2f})")
        return sized_intent
    
    def risk_check(self, intent: OrderIntent, bar: Bar) -> bool:
        """
        Perform risk checks on order intent.
        
        This method provides sensible defaults for risk management.
        Override for custom risk logic.
        
        Args:
            intent: Order intent to check
            bar: Current market data bar
            
        Returns:
            True if risk checks pass, False otherwise
        """
        # Basic risk checks
        if intent.quantity <= 0:
            self.context.logger.warning("Risk check failed: quantity <= 0")
            return False
        
        if intent.price and intent.price <= 0:
            self.context.logger.warning("Risk check failed: price <= 0")
            return False
        
        # Check day trade exposure (if applicable)
        # This would be implemented based on portfolio state
        
        self.context.logger.debug("Risk check passed")
        return True
    
    # Public entrypoint for the engine
    
    def handle_bar(self, bar: Bar) -> Iterable[OrderIntent]:
        """
        Main entrypoint for processing market data bars.
        
        This method orchestrates the strategy's response to market data:
        1. Generate order intents
        2. Size the intents
        3. Perform risk checks
        4. Return valid intents
        
        Args:
            bar: Market data bar to process
            
        Returns:
            Iterable of valid order intents
        """
        # Generate intents from strategy logic
        intents = list(self.generate_intents(bar))
        
        valid_intents = []
        
        for intent in intents:
            # Size the intent
            sized_intent = self.size_intent(intent, bar)
            
            # Perform risk checks
            if self.risk_check(sized_intent, bar):
                valid_intents.append(sized_intent)
            else:
                self.context.logger.warning(f"Risk check failed for intent: {sized_intent}")
        
        return valid_intents
    
    # Utility methods
    
    def get_state(self, key: str, default: Any = None) -> Any:
        """
        Get value from strategy state.
        
        Args:
            key: State key
            default: Default value if key not found
            
        Returns:
            State value or default
        """
        return self._state.get(key, default)
    
    def set_state(self, key: str, value: Any) -> None:
        """
        Set value in strategy state.
        
        Args:
            key: State key
            value: State value
        """
        self._state[key] = value
    
    def update_state(self, updates: Dict[str, Any]) -> None:
        """
        Update multiple state values.
        
        Args:
            updates: Dictionary of state updates
        """
        self._state.update(updates)
    
    def clear_state(self) -> None:
        """Clear all strategy state."""
        self._state.clear()
    
    def __str__(self) -> str:
        """String representation of the strategy."""
        return f"{self.name}(universe={len(self.config.universe)} symbols)"
    
    def __repr__(self) -> str:
        """Detailed string representation of the strategy."""
        return (f"{self.__class__.__name__}("
                f"config={self.config}, "
                f"context={self.context})") 