# B3 Market Configuration – Modal (June 2025)
market:
  trading_hours:
    open: "10:00"          # continuous session starts
    close: "16:55"         # continuous session ends; closing auction 16:55-17:00
    timezone: "America/Sao_Paulo"
  
  # Market parameters
  selic_rate: 0.15         # Current Brazilian SELIC rate (15.0% - 2025)
  trading_days_per_year: 252  # Brazilian market standard

  # Daily Factor Configuration
  daily_factor:
    source: 'bcb_official_api'
    
    # Advanced Transformation Configuration
    transformation:
      method: 'multiplicative'  # Options: 'multiplicative', 'exponential', 'compound'
      annualization_factor: 252.0  # Trading days per year
      compound_frequency: 1  # For compound method
    
    # Advanced Validation Configuration
    validation:
      strategies:  # Multiple validation methods can be applied
        - method: 'iqr'
          multiplier: 1.5
        - method: 'zscore'
          threshold: 3.0
        - method: 'rolling_window'
          window_size: 30
      
      bounds:
        min_factor: 0.95   # Configurable lower bound
        max_factor: 1.05   # Configurable upper bound
    
    interpolation:
      method: 'time'
      limit_direction: 'both'
      max_consecutive_interpolations: 5
    cache:
      directory: 'data/daily_factors/'
      format: 'parquet'
    
    logging:
      level: 'INFO'
      output:
        - console
        - file

  # Transaction costs
  costs:
    # --- mandatory B3 fees ---
    emolument: 0.00005                 # 0.005 % negotiation fee
    settlement_day_trade: 0.00018      # 0.018 % settlement fee (day-trade)
    settlement_swing_trade: 0.00025    # 0.025 % settlement fee (overnight)

    # --- Modal brokerage (electronic only) ---
    brokerage_fee: 0.0                 # zero brokerage via web/app
    min_brokerage: 0.0                 # no minimum charge
    iss_rate: 0.05                     # up to 5 % ISS on brokerage (currently 0 because brokerage = 0)

# Tax Configuration
taxes:
  swing_trade: 0.15        # 15 % capital-gains tax
  day_trade: 0.20          # 20 % capital-gains tax
  exemption_limit: 20000   # tax-free sales ceiling for non-day-trade (BRL/month)
  irrf_swing_rate: 0.00005 # 0.005% IRRF withholding on swing-trade sale value
  irrf_day_rate: 0.01      # 1% IRRF withholding on day-trade profit

# Portfolio Settings
portfolio:
  initial_cash: 100000     # starting capital in BRL
  max_positions: 10
  position_sizing: "equal_weight"

# Enhanced Settlement Configuration
settlement:
  cycle_days: 2                    # T+2 settlement cycle
  timezone: "America/Sao_Paulo"    # Market timezone for precise timing
  strict_mode: true                # Enforce rigorous settlement rules
  holiday_calendar: "b3"           # Use B3 holiday calendar
  max_retry_attempts: 3            # Maximum settlement retry attempts
  auto_process_settlements: true   # Automatically process due settlements

# Enhanced Loss Carryforward Configuration
loss_carryforward:
  max_tracking_years: null              # null = perpetual carryforward (Brazilian law 2025)
  global_loss_limit: null               # No limit on accumulated losses (Brazilian law 2025)
  asset_specific_tracking: true         # Enable per-asset loss tracking
  temporal_management: true             # Enable timestamp-based loss management
  audit_trail_enabled: true             # Enable comprehensive audit trail generation
  auto_prune_old_losses: false          # Disabled - losses never expire (Brazilian law 2025)
  partial_application: true             # Enable partial loss application
  performance_caching: true             # Enable performance optimization with caching
  
  # Brazilian Regulatory Compliance (2025)
  regulatory_compliance:
    max_offset_percentage: 0.30         # Maximum 30% loss offset against capital gains
    capital_gains_only: true            # Losses can ONLY offset capital gains
    perpetual_carryforward: true        # No time limit for loss carryforward
    cvm_compliance: true                # CVM (Brazilian Securities Commission) compliance
    receita_federal_compliance: true    # Receita Federal compliance
    
  # Audit and Reporting
  audit_requirements:
    detailed_loss_tracking: true        # Track individual loss records
    application_history: true           # Track loss application history
    regulatory_reporting: true          # Enable regulatory reporting
    compliance_validation: true         # Validate compliance with Brazilian law

# Performance & Monitoring Configuration
performance:
  enable_caching: true             # Enable LRU caching for performance
  cache_size: 128                  # Maximum cache entries
  enable_profiling: false          # Enable performance profiling
  log_level: "INFO"                # Logging level (DEBUG, INFO, WARNING, ERROR)
  audit_trail_retention_days: 365  # Days to retain audit trails
  backup_frequency_hours: 24       # Hours between automatic backups

# Compliance & Regulatory Configuration
compliance:
  regulatory_framework: "brazilian" # Regulatory framework (brazilian, international)
  tax_year_start: 1                # Tax year start month (1 = January)
  reporting_frequency: "monthly"   # Reporting frequency (daily, weekly, monthly)
  auto_export_audit_trails: true   # Automatically export audit trails
  regulatory_updates_enabled: true # Enable automatic regulatory updates
  compliance_checks_enabled: true  # Enable automatic compliance validation

# Error Handling & Resilience Configuration
error_handling:
  max_retry_attempts: 3            # Maximum retry attempts for failed operations
  graceful_degradation: true       # Enable graceful degradation on errors
  fallback_strategies: true        # Enable fallback strategies
  error_logging_level: "ERROR"     # Error logging level
  auto_recovery_enabled: true      # Enable automatic error recovery
  circuit_breaker_enabled: false   # Enable circuit breaker pattern

# Advanced Features Configuration
advanced:
  real_time_processing: false      # Enable real-time processing mode
  batch_processing_size: 1000      # Batch size for bulk operations
  parallel_processing: false       # Enable parallel processing
  memory_optimization: true        # Enable memory optimization
  lazy_loading: true               # Enable lazy loading for large datasets
  compression_enabled: true        # Enable data compression for storage

# SGS Data Configuration
sgs:
  # Banco Central SGS Series Configuration
  # Series ID: Series Name
  series:
    11: "Selic Interest Rate"      # Brazilian benchmark interest rate
    12: "CDI Interest Rate"        # Interbank deposit rate  
    433: "IPCA Inflation Index"    # Consumer price index
  
  # API Configuration
  api:
    base_url: "http://api.bcb.gov.br/dados/serie/bcdata.sgs"
    timeout: 30                    # Request timeout in seconds
    max_retries: 3                 # Maximum retry attempts
    user_agent: "quant_b3_backtest/1.0"
  
  # Data Processing Configuration
  processing:
    cache_enabled: true            # Enable data caching
    save_processed: true           # Save processed data to files
    data_path: "data/sgs"          # Path for SGS data storage
    normalization_method: "LOCF"   # Last Observation Carried Forward
  
  # Data Quality Validation
  validation:
    enable_quality_checks: true    # Enable data quality validation
    interest_rate_range: [0, 100]  # Valid range for interest rates (%)
    inflation_range: [-50, 100]    # Valid range for inflation (%)
    min_data_points: 10            # Minimum required data points