# B3 Market Configuration – Modal (June 2025)
market:
  trading_hours:
    open: "10:00"          # continuous session starts
    close: "16:55"         # continuous session ends; closing auction 16:55-17:00
    timezone: "America/Sao_Paulo"
  
  # Market parameters
  selic_rate: 0.15         # Current Brazilian SELIC rate (15.0% - 2025)
  trading_days_per_year: 252  # Brazilian market standard
  
  # Price and lot size conventions
  tick_size: 0.01          # Minimum price increment (R$ 0.01)
  round_lot_size: 100      # Standard lot size (multiples of 100 shares)
  min_quantity: 1          # Minimum order quantity
  allow_fractional_lots: true  # Allow odd lot orders (fractional book)
  enforce_price_ticks: true    # Enforce price tick normalization
  enforce_lot_sizes: true      # Enforce lot size validation

  # Transaction costs
  costs:
    # --- mandatory B3 fees ---
    emolument: 0.00005                 # 0.005 % negotiation fee
    settlement_day_trade: 0.00018      # 0.018 % settlement fee (day-trade)
    settlement_swing_trade: 0.00025    # 0.025 % settlement fee (overnight)

    # --- Modal brokerage (electronic only) ---
    brokerage_fee: 0.0                 # zero brokerage via web/app
    min_brokerage: 0.0                 # no minimum charge
    iss_rate: 0.05                     # up to 5 % ISS on brokerage (currently 0 because brokerage = 0)

# Tax Configuration - Brazilian PF Rules (July 2025)
taxes:
  # Tax rates for individual taxpayers
  swing_trade: 0.15        # 15% on monthly net profit from common operations
  day_trade: 0.20          # 20% on monthly net profit from day trading
  
  # Exemption for individual taxpayers (swing trade only)
  swing_exemption_limit: 20000   # R$ 20,000/month - sales ≤ this amount are tax exempt
  
  # IRRF (withholding tax) - Credit against final tax liability
  irrf_swing_rate: 0.00005 # 0.005% IRRF on gross sales (swing trade) - credit only
  irrf_day_rate: 0.01      # 1% IRRF on net profit per operation (day trade) - credit only
  
  # Individual taxpayer settings (no 30% limit)
  person_type: "individual"         # individual = individual taxpayer, corporate = corporate taxpayer
  max_loss_offset_percentage: 1.0  # 100% - individuals can offset up to 100% of profit
  loss_carryforward_perpetual: true # Losses are carried forward indefinitely

# Portfolio Settings
portfolio:
  initial_cash: 100000     # starting capital in BRL
  max_positions: 10
  position_sizing: "equal_weight"

# Enhanced Settlement Configuration
settlement:
  cycle_days: 2                    # T+2 settlement cycle
  timezone: "America/Sao_Paulo"    # Market timezone for precise timing
  strict_mode: true                # Enforce rigorous settlement rules
  holiday_calendar: "b3"           # Use B3 holiday calendar
  max_retry_attempts: 3            # Maximum settlement retry attempts
  auto_process_settlements: true   # Automatically process due settlements

# Enhanced Loss Carryforward Configuration
loss_carryforward:
  max_tracking_years: null              # null = perpetual carryforward (Brazilian law 2025)
  global_loss_limit: null               # No limit on accumulated losses (Brazilian law 2025)
  asset_specific_tracking: true         # Enable per-asset loss tracking
  temporal_management: true             # Enable timestamp-based loss management
  audit_trail_enabled: true             # Enable comprehensive audit trail generation
  auto_prune_old_losses: false          # Disabled - losses never expire (Brazilian law 2025)
  partial_application: true             # Enable partial loss application
  performance_caching: true             # Enable performance optimization with caching
  
  # Brazilian Regulatory Compliance (2025) - Individual Taxpayers
  regulatory_compliance:
    max_offset_percentage: 1.0          # 100% loss offset for individuals (no 30% limit)
    capital_gains_only: true            # Losses can ONLY offset capital gains
    perpetual_carryforward: true        # No time limit for loss carryforward
    cvm_compliance: true                # CVM (Brazilian Securities Commission) compliance
    receita_federal_compliance: true    # Receita Federal compliance
    person_type: "individual"           # Individual taxpayer rules (IN RFB 1.585/2015)
    
  # Audit and Reporting
  audit_requirements:
    detailed_loss_tracking: true        # Track individual loss records
    application_history: true           # Track loss application history
    regulatory_reporting: true          # Enable regulatory reporting
    compliance_validation: true         # Validate compliance with Brazilian law

# Order Management Configuration - Simplified for Backtesting
# Only essential market utilities are used (price ticks, lot sizes)

# Performance & Monitoring Configuration
performance:
  enable_caching: true             # Enable LRU caching for performance
  cache_size: 128                  # Maximum cache entries
  enable_profiling: false          # Enable performance profiling
  log_level: "INFO"                # Logging level (DEBUG, INFO, WARNING, ERROR)
  audit_trail_retention_days: 365  # Days to retain audit trails
  backup_frequency_hours: 24       # Hours between automatic backups

# Compliance & Regulatory Configuration
compliance:
  regulatory_framework: "brazilian" # Regulatory framework (brazilian, international)
  tax_year_start: 1                # Tax year start month (1 = January)
  reporting_frequency: "monthly"   # Reporting frequency (daily, weekly, monthly)
  auto_export_audit_trails: true   # Automatically export audit trails
  regulatory_updates_enabled: true # Enable automatic regulatory updates
  compliance_checks_enabled: true  # Enable automatic compliance validation

# Error Handling & Resilience Configuration
error_handling:
  max_retry_attempts: 3            # Maximum retry attempts for failed operations
  graceful_degradation: true       # Enable graceful degradation on errors
  fallback_strategies: true        # Enable fallback strategies
  error_logging_level: "ERROR"     # Error logging level
  auto_recovery_enabled: true      # Enable automatic error recovery
  circuit_breaker_enabled: false   # Enable circuit breaker pattern

# Advanced Features Configuration
advanced:
  real_time_processing: false      # Enable real-time processing mode
  batch_processing_size: 1000      # Batch size for bulk operations
  parallel_processing: false       # Enable parallel processing
  memory_optimization: true        # Enable memory optimization
  lazy_loading: true               # Enable lazy loading for large datasets
  compression_enabled: true        # Enable data compression for storage

# Benchmark Configuration
benchmark:
  enabled: true                    # Enable benchmark analysis for all backtests
  symbol: "IBOV"                   # Default benchmark symbol (Bovespa Index)
  auto_load: true                  # Automatically load benchmark data
  required: true                   # Require benchmark data for backtest completion
  data_sources: ["csv", "parquet", "yahoo_finance"]  # Priority order for data sources (Yahoo Finance preferred)
  risk_free_rate_override: null    # Override SELIC rate if needed (null = use SELIC from market config)

# SGS Data Configuration
sgs:
  # Banco Central SGS Series Configuration
  # Series ID: Series Name
  series:
    11: "Selic Interest Rate"      # Brazilian benchmark interest rate
    12: "CDI Interest Rate"        # Interbank deposit rate  
    433: "IPCA Inflation Index"    # Consumer price index
  
  # API Configuration
  api:
    base_url: "http://api.bcb.gov.br/dados/serie/bcdata.sgs"
    timeout: 30                    # Request timeout in seconds
    max_retries: 3                 # Maximum retry attempts
    user_agent: "quant_b3_backtest/1.0"
  
  # Data Processing Configuration
  processing:
    cache_enabled: true            # Enable data caching
    save_processed: true           # Save processed data to files
    data_path: "data/sgs"          # Path for SGS data storage
    normalization_method: "LOCF"   # Last Observation Carried Forward
  
  # Data Quality Validation
  validation:
    enable_quality_checks: true    # Enable data quality validation
    interest_rate_range: [0, 100]  # Valid range for interest rates (%)
    inflation_range: [-50, 100]    # Valid range for inflation (%)
    min_data_points: 10            # Minimum required data points
  
  # Strict Mode Configuration - No Fallbacks for SELIC Data
  strict_mode:
    enabled: true                  # Enable strict mode (no fallback rates)
    require_selic_data: true       # Require SELIC data for backtest execution
    minimum_coverage_percentage: 95.0  # Require 95% data coverage
    fail_on_missing_data: true     # Fail backtest if data is missing
    allow_partial_data: false      # Do not allow partial data usage
    
  # Data Quality Thresholds for Strict Mode
  quality_thresholds:
    minimum_data_points: 100       # Minimum SELIC data points required
    maximum_gap_days: 5            # Maximum consecutive days without data
    rate_validity_range: [0.001, 100.0]  # Valid SELIC rate range (0.1% to 10,000%)
    outlier_threshold: 3.0         # Standard deviations for outlier detection
    minimum_coverage_days: 30      # Minimum days of data required for validation

