//! Genome to StrategyConfig/TOML conversion.

use crate::error::ConversionError;
use crate::genome::{BlockType, StrategyGenome};
use crate::param_ranges::ParamRanges;
use backtester_strategy::config::{
    PipelineStep, RebalanceConfig, StrategyConfig, StrategyConstraints, StrategyMetadata,
};
use std::collections::HashMap;

/// Converter for genomes to StrategyConfig/TOML.
pub struct GenomeConverter {
    param_ranges: ParamRanges,
}

impl Default for GenomeConverter {
    fn default() -> Self {
        Self::new()
    }
}

impl GenomeConverter {
    /// Create a new converter.
    pub fn new() -> Self {
        Self {
            param_ranges: ParamRanges::new(),
        }
    }

    /// Create a converter with custom parameter ranges.
    pub fn with_ranges(param_ranges: ParamRanges) -> Self {
        Self { param_ranges }
    }

    /// Convert a genome to StrategyConfig.
    pub fn to_strategy_config(
        &self,
        genome: &StrategyGenome,
    ) -> Result<StrategyConfig, ConversionError> {
        // Sort genes by block type order
        let mut genes = genome.genes.clone();
        genes.sort_by_key(|g| g.block_type.order());

        // Convert genes to pipeline steps
        let pipeline: Vec<PipelineStep> = genes
            .iter()
            .map(|gene| {
                // Get default params and merge with gene params
                let mut params = if let Some(block_spec) = self.param_ranges.get_block(&gene.block_id)
                {
                    block_spec.default_params()
                } else {
                    HashMap::new()
                };

                // Override with gene-specific params
                for (key, value) in &gene.params {
                    params.insert(key.clone(), value.clone());
                }

                // Convert ParamValue to toml::Value
                let toml_params: HashMap<String, toml::Value> =
                    params.iter().map(|(k, v)| (k.clone(), v.to_toml_value())).collect();

                PipelineStep {
                    step_type: gene.block_type.as_str().to_string(),
                    block_id: gene.block_id.clone(),
                    params: toml_params,
                    enabled: true,
                }
            })
            .collect();

        // Create strategy metadata
        let metadata = StrategyMetadata {
            id: format!("scg_gen{}_{}", genome.generation, &genome.id.to_string()[..8]),
            version: "1.0.0".into(),
            description: format!(
                "Generated by SCG, generation {}, {} blocks",
                genome.generation,
                genome.genes.len()
            ),
            author: "SCG".into(),
        };

        // Extract constraints from sizing block if present
        let constraints = self.extract_constraints(genome);

        Ok(StrategyConfig {
            strategy: metadata,
            pipeline,
            rebalance: RebalanceConfig::default(),
            constraints,
            defaults: HashMap::new(),
        })
    }

    /// Convert a genome to TOML string.
    pub fn to_toml(&self, genome: &StrategyGenome) -> Result<String, ConversionError> {
        let config = self.to_strategy_config(genome)?;
        toml::to_string_pretty(&config).map_err(ConversionError::TomlSerialize)
    }

    /// Convert a genome to JSON string.
    pub fn to_json(&self, genome: &StrategyGenome) -> Result<String, ConversionError> {
        serde_json::to_string_pretty(genome).map_err(ConversionError::JsonSerialize)
    }

    /// Extract constraints from sizing block parameters.
    fn extract_constraints(&self, genome: &StrategyGenome) -> StrategyConstraints {
        let mut constraints = StrategyConstraints::default();

        // Find sizing block and extract max_weight and max_positions
        for gene in genome.genes_by_type(BlockType::Sizing) {
            if let Some(max_weight) = gene.get_param("max_weight") {
                constraints.max_weight_per_asset = max_weight.as_f64();
            }
            if let Some(max_positions) = gene.get_param("max_positions") {
                constraints.max_positions = Some(max_positions.as_i64() as usize);
            }
        }

        constraints
    }
}

/// Extension trait for StrategyGenome to add conversion methods.
impl StrategyGenome {
    /// Convert to StrategyConfig.
    pub fn to_strategy_config(&self) -> Result<StrategyConfig, ConversionError> {
        GenomeConverter::new().to_strategy_config(self)
    }

    /// Convert to TOML string.
    pub fn to_toml(&self) -> Result<String, ConversionError> {
        GenomeConverter::new().to_toml(self)
    }

    /// Convert to JSON string.
    pub fn to_json(&self) -> Result<String, ConversionError> {
        GenomeConverter::new().to_json(self)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::genome::{BlockGene, ParamValue};

    #[test]
    fn test_to_strategy_config() {
        let genome = StrategyGenome::new(vec![
            BlockGene::new(
                BlockType::Selection,
                "momentum",
                vec![
                    ("lookback_days", ParamValue::int(126, 21, 252, 21)),
                    ("top_pct", ParamValue::float(20.0, 5.0, 50.0, 5.0)),
                ],
            ),
            BlockGene::new(
                BlockType::Sizing,
                "equal_weight",
                vec![
                    ("max_weight", ParamValue::float(0.2, 0.05, 0.5, 0.05)),
                    ("max_positions", ParamValue::int(10, 5, 50, 5)),
                ],
            ),
        ]);

        let converter = GenomeConverter::new();
        let config = converter.to_strategy_config(&genome).unwrap();

        assert_eq!(config.pipeline.len(), 2);
        assert_eq!(config.pipeline[0].step_type, "selection");
        assert_eq!(config.pipeline[0].block_id, "momentum");
        assert_eq!(config.pipeline[1].step_type, "sizing");
        assert_eq!(config.pipeline[1].block_id, "equal_weight");
    }

    #[test]
    fn test_to_toml() {
        let genome = StrategyGenome::new(vec![
            BlockGene::new(
                BlockType::Selection,
                "momentum",
                vec![("lookback_days", ParamValue::int(126, 21, 252, 21))],
            ),
            BlockGene::with_defaults(BlockType::Sizing, "equal_weight"),
        ]);

        let converter = GenomeConverter::new();
        let toml_str = converter.to_toml(&genome).unwrap();

        // Should contain strategy section
        assert!(toml_str.contains("[strategy]"));
        // Should contain pipeline
        assert!(toml_str.contains("[[pipeline]]"));
        // Should contain block_id
        assert!(toml_str.contains("momentum"));
        assert!(toml_str.contains("equal_weight"));
    }

    #[test]
    fn test_pipeline_order() {
        // Genes in wrong order should be sorted
        let genome = StrategyGenome::new(vec![
            BlockGene::with_defaults(BlockType::Sizing, "equal_weight"),
            BlockGene::with_defaults(BlockType::Exit, "stop_loss"),
            BlockGene::with_defaults(BlockType::Selection, "momentum"),
            BlockGene::with_defaults(BlockType::Entry, "ma_crossover"),
        ]);

        let converter = GenomeConverter::new();
        let config = converter.to_strategy_config(&genome).unwrap();

        // Should be sorted: Selection -> Entry -> Exit -> Sizing
        assert_eq!(config.pipeline[0].step_type, "selection");
        assert_eq!(config.pipeline[1].step_type, "entry");
        assert_eq!(config.pipeline[2].step_type, "exit");
        assert_eq!(config.pipeline[3].step_type, "sizing");
    }

    #[test]
    fn test_constraints_extraction() {
        let genome = StrategyGenome::new(vec![
            BlockGene::with_defaults(BlockType::Selection, "momentum"),
            BlockGene::new(
                BlockType::Sizing,
                "equal_weight",
                vec![
                    ("max_weight", ParamValue::float(0.15, 0.05, 0.5, 0.05)),
                    ("max_positions", ParamValue::int(15, 5, 50, 5)),
                ],
            ),
        ]);

        let converter = GenomeConverter::new();
        let config = converter.to_strategy_config(&genome).unwrap();

        assert!((config.constraints.max_weight_per_asset - 0.15).abs() < 0.001);
        assert_eq!(config.constraints.max_positions, Some(15));
    }
}

